--- #YAML:1.0
name:                Business-PayPal-API
version:             0.51
abstract:            PayPal API
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    SOAP::Lite:                    0.67
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Scott Wiersdorf <scott@perlcode.org>
